### ISSUE TITLE
Doesnt connect to Meshtastic Public MQTT?

### ISSUE THREAD

**Issue by Talie5in** [tcivie/meshtastic-metrics-exporter#26]
pointing the .env to the meshtastic public mqtt just throws this in the exporter logs

```
Connected with result code Unsupported protocol version
Connected with result code Unsupported protocol version
Connected with result code Unsupported protocol version
Connected with result code Unsupported protocol version
```

**Comment by Talie5in** [comment]
Note: Created a Bridge within your docker-compose

Add to volumes:
```  mosquitto_data: ```

Added mosquitto to service

```
mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mesh-bridge
```

and mosquitto.conf that i stored into ./docker/mosquitto/mosquitto.conf
```
allow_anonymous true
listener 1883

connection bridge-01
address mqtt.meshtastic.org:1883

topic msh/ANZ/# out 0
topic msh/ANZ/# in 0

remote_username meshdev
remote_password large4cats
```

in .env
point to machine ip (192.168.1.50) instead of localhost or 127.0.0.1 as its not bound that way via docker :)
